<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('cities')
            ->insert([
                // Ahuachapán
                ['name' => 'Ahuachapán', 'department_id' => 1],
                ['name' => 'Apaneca', 'department_id' => 1],
                ['name' => 'Concepción de Ataco', 'department_id' => 1],
                ['name' => 'Tacuba', 'department_id' => 1],
                ['name' => 'Atiquizaya', 'department_id' => 1],
                ['name' => 'El Refugio', 'department_id' => 1],
                ['name' => 'San Lorenzo', 'department_id' => 1],
                ['name' => 'Turín', 'department_id' => 1],
                ['name' => 'Guaymango', 'department_id' => 1],
                ['name' => 'Jujutla', 'department_id' => 1],
                ['name' => 'San Francisco Menéndez', 'department_id' => 1],
                ['name' => 'San Pedro Puxtla', 'department_id' => 1],

                // Santa Ana
                ['name' => 'Santa Ana', 'department_id' => 2],
                ['name' => 'Coatepeque', 'department_id' => 2],
                ['name' => 'El Congo', 'department_id' => 2],
                ['name' => 'Masahuat', 'department_id' => 2],
                ['name' => 'Metapán', 'department_id' => 2],
                ['name' => 'Santa Rosa Guachipilín', 'department_id' => 2],
                ['name' => 'Texistepeque', 'department_id' => 2],
                ['name' => 'Candelaria de la Frontera', 'department_id' => 2],
                ['name' => 'Chalchuapa', 'department_id' => 2],
                ['name' => 'El Porvenir', 'department_id' => 2],
                ['name' => 'San Antonio Pajonal', 'department_id' => 2],
                ['name' => 'San Sebastián Salitrillo', 'department_id' => 2],
                ['name' => 'Santiago de la Frontera', 'department_id' => 2],

                // Sonsonate
                ['name' => 'Nahulingo', 'department_id' => 3],
                ['name' => 'San Antonio del Monte', 'department_id' => 3],
                ['name' => 'Santo Domingo de Guzmán', 'department_id' => 3],
                ['name' => 'Sonsonate', 'department_id' => 3],
                ['name' => 'Sonzacate', 'department_id' => 3],
                ['name' => 'Armenia', 'department_id' => 3],
                ['name' => 'Caluco', 'department_id' => 3],
                ['name' => 'Cuisnahuat', 'department_id' => 3],
                ['name' => 'Santa Isabel Ishuatán', 'department_id' => 3],
                ['name' => 'Izalco', 'department_id' => 3],
                ['name' => 'San Julián', 'department_id' => 3],
                ['name' => 'Juayúa', 'department_id' => 3],
                ['name' => 'Nahuizalco', 'department_id' => 3],
                ['name' => 'Salcoatitán', 'department_id' => 3],
                ['name' => 'Santa Catarina Masahuat', 'department_id' => 3],
                ['name' => 'Acajutla', 'department_id' => 3],

                // Chalatenango
                ['name' => 'Agua Caliente', 'department_id' => 4],
                ['name' => 'Dulce Nombre de María', 'department_id' => 4],
                ['name' => 'El Paraíso', 'department_id' => 4],
                ['name' => 'La Reina', 'department_id' => 4],
                ['name' => 'Nueva Concepción', 'department_id' => 4],
                ['name' => 'San Fernando', 'department_id' => 4],
                ['name' => 'San Francisco Morazán', 'department_id' => 4],
                ['name' => 'San Rafael', 'department_id' => 4],
                ['name' => 'Santa Rita', 'department_id' => 4],
                ['name' => 'Tejutla', 'department_id' => 4],
                ['name' => 'Citalá', 'department_id' => 4],
                ['name' => 'San Ignacio', 'department_id' => 4],
                ['name' => 'La Palma', 'department_id' => 4],
                ['name' => 'Arcatao', 'department_id' => 4],
                ['name' => 'Azacualpa', 'department_id' => 4],
                ['name' => 'Comalapa', 'department_id' => 4],
                ['name' => 'Concepción Quezaltepeque', 'department_id' => 4],
                ['name' => 'Chalatenango', 'department_id' => 4],
                ['name' => 'El Carrizal', 'department_id' => 4],
                ['name' => 'La Laguna', 'department_id' => 4],
                ['name' => 'Las Vueltas', 'department_id' => 4],
                ['name' => 'Nombre de Jesús', 'department_id' => 4],
                ['name' => 'Nueva Trinidad', 'department_id' => 4],
                ['name' => 'Ojos de Agua', 'department_id' => 4],
                ['name' => 'Potonico', 'department_id' => 4],
                ['name' => 'San Antonio de la Cruz', 'department_id' => 4],
                ['name' => 'San Antonio Los Ranchos', 'department_id' => 4],
                ['name' => 'San Isidro Labrador', 'department_id' => 4],
                ['name' => 'San Francisco Lempa', 'department_id' => 4],
                ['name' => 'San José Cancasque', 'department_id' => 4],
                ['name' => 'San José Las Flores', 'department_id' => 4],
                ['name' => 'San Luis del Carmen', 'department_id' => 4],
                ['name' => 'San Miguel de Mercedes', 'department_id' => 4],

                // La Libertad
                ['name' => 'Ciudad Arce', 'department_id' => 5],
                ['name' => 'San Juan Opico', 'department_id' => 5],
                ['name' => 'Chiltiupán', 'department_id' => 5],
                ['name' => 'Jicalapa', 'department_id' => 5],
                ['name' => 'La Libertad', 'department_id' => 5],
                ['name' => 'Tamanique', 'department_id' => 5],
                ['name' => 'Teotepeque', 'department_id' => 5],
                ['name' => 'Antiguo Cuscatlán', 'department_id' => 5],
                ['name' => 'Huizúcar', 'department_id' => 5],
                ['name' => 'Nuevo Cuscatlán', 'department_id' => 5],
                ['name' => 'San José Villanueva', 'department_id' => 5],
                ['name' => 'Zaragoza', 'department_id' => 5],
                ['name' => 'Quezaltepeque', 'department_id' => 5],
                ['name' => 'San Matías', 'department_id' => 5],
                ['name' => 'San Pablo Tacachico', 'department_id' => 5],
                ['name' => 'Colón', 'department_id' => 5],
                ['name' => 'Jayaque', 'department_id' => 5],
                ['name' => 'Sacacoyo', 'department_id' => 5],
                ['name' => 'Talnique', 'department_id' => 5],
                ['name' => 'Tepecoyo', 'department_id' => 5],
                ['name' => 'Comasagua', 'department_id' => 5],
                ['name' => 'Santa Tecla antes: Nueva San Salvador', 'department_id' => 5],

                 // San Salvador
                ['name' => 'Ayutuxtepeque', 'department_id' => 6],
                ['name' => 'Cuscatancingo', 'department_id' => 6],
                ['name' => 'Mejicanos', 'department_id' => 6],
                ['name' => 'San Salvador', 'department_id' => 6],
                ['name' => 'Delgado', 'department_id' => 6],
                ['name' => 'Ilopango', 'department_id' => 6],
                ['name' => 'San Martín', 'department_id' => 6],
                ['name' => 'Soyapango', 'department_id' => 6],
                ['name' => 'Tonacatepeque', 'department_id' => 6],
                ['name' => 'Aguilares', 'department_id' => 6],
                ['name' => 'El Paisnal', 'department_id' => 6],
                ['name' => 'Guazapa', 'department_id' => 6],
                ['name' => 'Apopa', 'department_id' => 6],
                ['name' => 'Nejapa', 'department_id' => 6],
                ['name' => 'Panchimalco', 'department_id' => 6],
                ['name' => 'Rosario de Mora', 'department_id' => 6],
                ['name' => 'San Marcos', 'department_id' => 6],
                ['name' => 'Santiago Texacuangos', 'department_id' => 6],
                ['name' => 'Santo Tomás', 'department_id' => 6],

                // Cuscatlán
                ['name' => 'Oratorio de Concepción', 'department_id' => 7],
                ['name' => 'San Bartolomé Perulapía', 'department_id' => 7],
                ['name' => 'San José Guayabal', 'department_id' => 7],
                ['name' => 'San Pedro Perulapán', 'department_id' => 7],
                ['name' => 'Suchitoto', 'department_id' => 7],
                ['name' => 'Candelaria', 'department_id' => 7],
                ['name' => 'Cojutepeque', 'department_id' => 7],
                ['name' => 'El Carmen', 'department_id' => 7],
                ['name' => 'El Rosario', 'department_id' => 7],
                ['name' => 'Monte San Juan', 'department_id' => 7],
                ['name' => 'San Cristóbal', 'department_id' => 7],
                ['name' => 'San Rafael Cedros', 'department_id' => 7],
                ['name' => 'San Ramón', 'department_id' => 7],
                ['name' => 'Santa Cruz Analquito', 'department_id' => 7],
                ['name' => 'Santa Cruz Michapa', 'department_id' => 7],
                ['name' => 'Tenancingo', 'department_id' => 7],

                 // La Paz
                ['name' => 'El Rosario', 'department_id' => 8],
                ['name' => 'Jerusalén', 'department_id' => 8],
                ['name' => 'Mercedes La Ceiba', 'department_id' => 8],
                ['name' => 'Paraíso de Osorio', 'department_id' => 8],
                ['name' => 'San Antonio Masahuat', 'department_id' => 8],
                ['name' => 'San Emigdio', 'department_id' => 8],
                ['name' => 'San Juan Tepezontes', 'department_id' => 8],
                ['name' => 'San Miguel Tepezontes', 'department_id' => 8],
                ['name' => 'San Pedro Nonualco', 'department_id' => 8],
                ['name' => 'Santa María Ostuma', 'department_id' => 8],
                ['name' => 'Santiago Nonualco', 'department_id' => 8],
                ['name' => 'San Luis La Herradura', 'department_id' => 8],
                ['name' => 'San Juan Nonualco', 'department_id' => 8],
                ['name' => 'San Rafael Obrajuelo', 'department_id' => 8],
                ['name' => 'Zacatecoluca', 'department_id' => 8],
                ['name' => 'Cuyultitán', 'department_id' => 8],
                ['name' => 'Olocuilta', 'department_id' => 8],
                ['name' => 'San Francisco Chinameca', 'department_id' => 8],
                ['name' => 'San Juan Talpa', 'department_id' => 8],
                ['name' => 'San Luis Talpa', 'department_id' => 8],
                ['name' => 'San Pedro Masahuat', 'department_id' => 8],
                ['name' => 'Tapalhuaca', 'department_id' => 8],

                // Cabañas
                ['name' => 'Dolores', 'department_id' => 9],
                ['name' => 'Guacotecti', 'department_id' => 9],
                ['name' => 'San Isidro', 'department_id' => 9],
                ['name' => 'Sensuntepeque', 'department_id' => 9],
                ['name' => 'Victoria', 'department_id' => 9],
                ['name' => 'Cinquera', 'department_id' => 9],
                ['name' => 'Ilobasco', 'department_id' => 9],
                ['name' => 'Jutiapa', 'department_id' => 9],
                ['name' => 'Tejutepeque', 'department_id' => 9],

                // San Vicente
                ['name' => 'Apastepeque', 'department_id' => 10],
                ['name' => 'San Esteban Catarina', 'department_id' => 10],
                ['name' => 'San Ildefonso', 'department_id' => 10],
                ['name' => 'San Lorenzo', 'department_id' => 10],
                ['name' => 'San Sebastián', 'department_id' => 10],
                ['name' => 'Santa Clara', 'department_id' => 10],
                ['name' => 'Santo Domingo', 'department_id' => 10],
                ['name' => 'Guadalupe', 'department_id' => 10],
                ['name' => 'San Cayetano Istepeque', 'department_id' => 10],
                ['name' => 'San Vicente', 'department_id' => 10],
                ['name' => 'Tecoluca', 'department_id' => 10],
                ['name' => 'Tepetitán', 'department_id' => 10],
                ['name' => 'Verapaz', 'department_id' => 10],

                 // Usulután
                ['name' => 'California', 'department_id' => 11],
                ['name' => 'Concepción Batres', 'department_id' => 11],
                ['name' => 'Ereguayquín', 'department_id' => 11],
                ['name' => 'Jucuarán', 'department_id' => 11],
                ['name' => 'Ozatlán', 'department_id' => 11],
                ['name' => 'Usulután', 'department_id' => 11],
                ['name' => 'San Dionisio', 'department_id' => 11],
                ['name' => 'Santa Elena', 'department_id' => 11],
                ['name' => 'Santa María', 'department_id' => 11],
                ['name' => 'Tecapán', 'department_id' => 11],
                ['name' => 'Alegría', 'department_id' => 11],
                ['name' => 'Berlín', 'department_id' => 11],
                ['name' => 'El Triunfo', 'department_id' => 11],
                ['name' => 'Estanzuelas', 'department_id' => 11],
                ['name' => 'Jucuapa', 'department_id' => 11],
                ['name' => 'Mercedes Umaña', 'department_id' => 11],
                ['name' => 'Nueva Granada', 'department_id' => 11],
                ['name' => 'San Buenaventura', 'department_id' => 11],
                ['name' => 'Santiago de María', 'department_id' => 11],
                ['name' => 'Jiquilisco', 'department_id' => 11],
                ['name' => 'Puerto El Triunfo', 'department_id' => 11],
                ['name' => 'San Agustín', 'department_id' => 11],
                ['name' => 'San Francisco Javier', 'department_id' => 11],

                // San Miguel
                ['name' => 'Comacarán', 'department_id' => 12],
                ['name' => 'Moncagua', 'department_id' => 12],
                ['name' => 'Chirilagua', 'department_id' => 12],
                ['name' => 'Quelepa', 'department_id' => 12],
                ['name' => 'San Miguel', 'department_id' => 12],
                ['name' => 'Uluazapa', 'department_id' => 12],
                ['name' => 'Carolina', 'department_id' => 12],
                ['name' => 'Ciudad Barrios', 'department_id' => 12],
                ['name' => 'Chapeltique', 'department_id' => 12],
                ['name' => 'Nuevo Edén de San Juan', 'department_id' => 12],
                ['name' => 'San Antonio del Mosco', 'department_id' => 12],
                ['name' => 'San Gerardo', 'department_id' => 12],
                ['name' => 'San Luis de La Reina', 'department_id' => 12],
                ['name' => 'Sesori', 'department_id' => 12],
                ['name' => 'Chinameca', 'department_id' => 12],
                ['name' => 'El Tránsito', 'department_id' => 12],
                ['name' => 'Lolotique', 'department_id' => 12],
                ['name' => 'Nueva Guadalupe', 'department_id' => 12],
                ['name' => 'San Jorge', 'department_id' => 12],
                ['name' => 'San Rafael Oriente', 'department_id' => 12],

                // Morazán
                ['name' => 'Arambala', 'department_id' => 13],
                ['name' => 'Cacaopera', 'department_id' => 13],
                ['name' => 'Corinto', 'department_id' => 13],
                ['name' => 'El Rosario', 'department_id' => 13],
                ['name' => 'Joateca', 'department_id' => 13],
                ['name' => 'Jocoaitique', 'department_id' => 13],
                ['name' => 'Meanguera', 'department_id' => 13],
                ['name' => 'Perquín', 'department_id' => 13],
                ['name' => 'San Fernando', 'department_id' => 13],
                ['name' => 'San Isidro', 'department_id' => 13],
                ['name' => 'Torola', 'department_id' => 13],
                ['name' => 'Chilanga', 'department_id' => 13],
                ['name' => 'Delicias de Concepción', 'department_id' => 13],
                ['name' => 'El Divisadero', 'department_id' => 13],
                ['name' => 'Gualococti', 'department_id' => 13],
                ['name' => 'Guatajiagua', 'department_id' => 13],
                ['name' => 'Jocoro', 'department_id' => 13],
                ['name' => 'Lolotiquillo', 'department_id' => 13],
                ['name' => 'Osicala', 'department_id' => 13],
                ['name' => 'San Carlos', 'department_id' => 13],
                ['name' => 'San Francisco Gotera', 'department_id' => 13],
                ['name' => 'San Simón', 'department_id' => 13],
                ['name' => 'Sensembra', 'department_id' => 13],
                ['name' => 'Sociedad', 'department_id' => 13],
                ['name' => 'Yamabal', 'department_id' => 13],
                ['name' => 'Yoloaiquín', 'department_id' => 13],

                // La Unión
                ['name' => 'Anamorós', 'department_id' => 14],
                ['name' => 'Bolívar', 'department_id' => 14],
                ['name' => 'Concepción de Oriente', 'department_id' => 14],
                ['name' => 'El Sauce', 'department_id' => 14],
                ['name' => 'Lislique', 'department_id' => 14],
                ['name' => 'Nueva Esparta', 'department_id' => 14],
                ['name' => 'Pasaquina', 'department_id' => 14],
                ['name' => 'Polorós', 'department_id' => 14],
                ['name' => 'San José La Fuente', 'department_id' => 14],
                ['name' => 'Santa Rosa de Lima', 'department_id' => 14],
                ['name' => 'Conchagua', 'department_id' => 14],
                ['name' => 'El Carmen', 'department_id' => 14],
                ['name' => 'Intipucá', 'department_id' => 14],
                ['name' => 'La Unión', 'department_id' => 14],
                ['name' => 'Meanguera del Golfo', 'department_id' => 14],
                ['name' => 'San Alejo', 'department_id' => 14],
                ['name' => 'Yayantique', 'department_id' => 14],
                ['name' => 'Yucuaiquín', 'department_id' => 14],
            ]);
    }
}
